//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDinghy.app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoDinghyWebEntities : DbContext
    {
        public GoDinghyWebEntities()
            : base("name=GoDinghyWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cmsContent> cmsContent { get; set; }
        public virtual DbSet<cmsContentType> cmsContentType { get; set; }
        public virtual DbSet<cmsContentTypeAllowedContentType> cmsContentTypeAllowedContentType { get; set; }
        public virtual DbSet<cmsContentVersion> cmsContentVersion { get; set; }
        public virtual DbSet<cmsContentXml> cmsContentXml { get; set; }
        public virtual DbSet<cmsDataType> cmsDataType { get; set; }
        public virtual DbSet<cmsDataTypePreValues> cmsDataTypePreValues { get; set; }
        public virtual DbSet<cmsDictionary> cmsDictionary { get; set; }
        public virtual DbSet<cmsDocument> cmsDocument { get; set; }
        public virtual DbSet<cmsDocumentType> cmsDocumentType { get; set; }
        public virtual DbSet<cmsLanguageText> cmsLanguageText { get; set; }
        public virtual DbSet<cmsMacro> cmsMacro { get; set; }
        public virtual DbSet<cmsMacroProperty> cmsMacroProperty { get; set; }
        public virtual DbSet<cmsMember> cmsMember { get; set; }
        public virtual DbSet<cmsMemberType> cmsMemberType { get; set; }
        public virtual DbSet<cmsPreviewXml> cmsPreviewXml { get; set; }
        public virtual DbSet<cmsPropertyData> cmsPropertyData { get; set; }
        public virtual DbSet<cmsPropertyType> cmsPropertyType { get; set; }
        public virtual DbSet<cmsPropertyTypeGroup> cmsPropertyTypeGroup { get; set; }
        public virtual DbSet<cmsTagRelationship> cmsTagRelationship { get; set; }
        public virtual DbSet<cmsTags> cmsTags { get; set; }
        public virtual DbSet<cmsTask> cmsTask { get; set; }
        public virtual DbSet<cmsTaskType> cmsTaskType { get; set; }
        public virtual DbSet<cmsTemplate> cmsTemplate { get; set; }
        public virtual DbSet<umbracoAccess> umbracoAccess { get; set; }
        public virtual DbSet<umbracoAccessRule> umbracoAccessRule { get; set; }
        public virtual DbSet<umbracoCacheInstruction> umbracoCacheInstruction { get; set; }
        public virtual DbSet<umbracoDeployChecksum> umbracoDeployChecksum { get; set; }
        public virtual DbSet<umbracoDeployDependency> umbracoDeployDependency { get; set; }
        public virtual DbSet<umbracoDomains> umbracoDomains { get; set; }
        public virtual DbSet<umbracoExternalLogin> umbracoExternalLogin { get; set; }
        public virtual DbSet<umbracoLanguage> umbracoLanguage { get; set; }
        public virtual DbSet<umbracoLog> umbracoLog { get; set; }
        public virtual DbSet<umbracoMigration> umbracoMigration { get; set; }
        public virtual DbSet<umbracoNode> umbracoNode { get; set; }
        public virtual DbSet<umbracoRedirectUrl> umbracoRedirectUrl { get; set; }
        public virtual DbSet<umbracoRelation> umbracoRelation { get; set; }
        public virtual DbSet<umbracoRelationType> umbracoRelationType { get; set; }
        public virtual DbSet<umbracoServer> umbracoServer { get; set; }
        public virtual DbSet<umbracoUser> umbracoUser { get; set; }
        public virtual DbSet<umbracoUser2app> umbracoUser2app { get; set; }
        public virtual DbSet<umbracoUser2NodeNotify> umbracoUser2NodeNotify { get; set; }
        public virtual DbSet<umbracoUser2NodePermission> umbracoUser2NodePermission { get; set; }
        public virtual DbSet<umbracoUserType> umbracoUserType { get; set; }
    }
}
