//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDinghy.app
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public umbracoNode()
        {
            this.cmsContent = new HashSet<cmsContent>();
            this.cmsContentType = new HashSet<cmsContentType>();
            this.cmsDataType = new HashSet<cmsDataType>();
            this.cmsDocument = new HashSet<cmsDocument>();
            this.cmsDocumentType = new HashSet<cmsDocumentType>();
            this.cmsMemberType = new HashSet<cmsMemberType>();
            this.cmsPropertyData = new HashSet<cmsPropertyData>();
            this.cmsTask = new HashSet<cmsTask>();
            this.cmsTemplate = new HashSet<cmsTemplate>();
            this.umbracoAccess = new HashSet<umbracoAccess>();
            this.umbracoAccess1 = new HashSet<umbracoAccess>();
            this.umbracoAccess2 = new HashSet<umbracoAccess>();
            this.umbracoDomains = new HashSet<umbracoDomains>();
            this.umbracoNode1 = new HashSet<umbracoNode>();
            this.umbracoRelation = new HashSet<umbracoRelation>();
            this.umbracoRelation1 = new HashSet<umbracoRelation>();
            this.umbracoUser2NodeNotify = new HashSet<umbracoUser2NodeNotify>();
            this.umbracoUser2NodePermission = new HashSet<umbracoUser2NodePermission>();
            this.umbracoNode11 = new HashSet<umbracoNode>();
            this.umbracoNode3 = new HashSet<umbracoNode>();
            this.cmsMember1 = new HashSet<cmsMember>();
        }
    
        public int id { get; set; }
        public bool trashed { get; set; }
        public int parentID { get; set; }
        public Nullable<int> nodeUser { get; set; }
        public int level { get; set; }
        public string path { get; set; }
        public int sortOrder { get; set; }
        public System.Guid uniqueID { get; set; }
        public string text { get; set; }
        public Nullable<System.Guid> nodeObjectType { get; set; }
        public System.DateTime createDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsContent> cmsContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsContentType> cmsContentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsDataType> cmsDataType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsDocument> cmsDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsDocumentType> cmsDocumentType { get; set; }
        public virtual cmsMember cmsMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsMemberType> cmsMemberType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsPropertyData> cmsPropertyData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsTask> cmsTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsTemplate> cmsTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoAccess> umbracoAccess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoAccess> umbracoAccess1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoAccess> umbracoAccess2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoDomains> umbracoDomains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoNode> umbracoNode1 { get; set; }
        public virtual umbracoNode umbracoNode2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoRelation> umbracoRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoRelation> umbracoRelation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoUser2NodeNotify> umbracoUser2NodeNotify { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoUser2NodePermission> umbracoUser2NodePermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoNode> umbracoNode11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoNode> umbracoNode3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsMember> cmsMember1 { get; set; }
    }
}
